local_backend: true

backend:
  name: git-gateway

media_folder: '_media/uploads'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    publish_mode: editorial_workflow
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Categories', name: 'categories', widget: 'string' }
      - { label: 'Author', name: 'author', widget: "relation", collection: "authors", search_fields: ["name"], value_field: "name", display_fields: ["name", "display_name"] }
      - { label: 'Extract', name: 'extract', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'authors'
    label: 'Authors'
    folder: '_authors/'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'author' }
      - { label: 'Short Name', name: 'name', widget: 'string' }
      - { label: 'Display Name', name: 'display_name', widget: 'string' }
      - { label: 'Position', name: 'position', widget: 'string' }
      - { label: 'Photo', name: 'image', widget: 'image' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'config'
    label: 'Config'
    editor:
      preview: false
    files:
      - label: 'Navigation'
        name: 'navigation'
        file: '_data/navigation.yml'
        fields:
          - label: 'Navigation Items'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Link, name: link, widget: string }
      - label: 'Sash'
        name: 'sash'
        file: '_data/sash.yml'
        fields:
          - label: 'Sash Content'
            name: 'content'
            widget: 'string'
      - label: 'Featured Post'
        name: 'fp'
        file: '_data/featured.yml'
        fields:
          - label: 'Post'
            name: 'post'
            widget: "relation"
            collection: "blog"
            search_fields: ["title"]
            value_field: "title"
            display_fields: ["title"]
  - name: 'issues'
    label: 'Journal Issues'
    editor:
      preview: false
    files:
      - label: 'Issues'
        name: 'issues'
        file: '_data/issues.yml'
        fields:
          - label: 'Items'
            name: 'items'
            widget: 'list'
            fields:
              - { label: Name, name: name, widget: string }
              - { label: 'Extract', name: 'extract', widget: 'string' }
              - { label: File, name: file, widget: file }
              - { label: 'Publish Date', name: 'date', widget: 'datetime' }